name: General checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-typing:
    # TODO: switch to main after fix lends
    uses: Lightning-AI/utilities/.github/workflows/check-typing.yml@main
    with:
      actions-ref: main

  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@v0.11.5
    with:
      azure-dir: ""

  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@v0.11.5
    with:
      actions-ref: v0.11.3.post0
      import-name: "litdata"
      artifact-name: dist-packages-${{ github.sha }}
      testing-matrix: |
        {
          "os": ["ubuntu-latest", "macos-13", "windows-latest"],
          "python-version": ["3.8", "3.10"]
        }

  check-docs:
    uses: Lightning-AI/utilities/.github/workflows/check-docs.yml@v0.11.5
    with:
      requirements-file: "requirements/docs.txt"
